<a href="https://colab.research.google.com/github/scoutaiken/Linear_Algebra_Coding_projects/blob/main/Gram_Schmidt_Orthogonization_Process_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
# create a vector:
r = np.matrix('3; 0; 3; 0')
r

matrix([[3],
        [0],
        [3],
        [0]])

In [ ]:
# create a vector as an array:
s = np.array([3, 0, 3, 0])
s

array([3, 0, 3, 0])

In [ ]:
s.dot(s)

18

In [ ]:
# the size of s:
np.sqrt(s.dot(s))

5.477225575051661

Using the Gram-Schmidt Orthonormalization Process

In [ ]:
# the messy vectors:
r1 = np.array([3, 0, 3, 0])
r2 = np.array([3, 2, 3, 3])
r3 = np.array([-7, -4, -5, -6])
r4 = np.array([-7, -3, -11, 2])

In [ ]:
# Find the first nice basis vector:
t1 = r1
# Subtract off the nice basis vectors (nothing yet):

# Find the size of t1:
n1 = np.sqrt(t1.dot(t1))

# So u1 = (1/n1) * t1
u1 = (1/n1) * t1
n1

4.242640687119285

In [ ]:
# Verify that u1 is size 1 and is othoganal to all other u vectors
u1.dot(u1)

1.0000000000000002

In [ ]:
# Find the second nice basis vector:
t2 = r2 - (r2.dot(u1)) * u1
# Subtract off the nice basis vectors:

# Find the size of t2:
n2 = np.sqrt(t2.dot(t2))

# So u2 = (1/n2) * t2
u2 = (1/n2) * t2
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [ ]:
print("The sqaured size of u2 = ", u2.dot(u2))
print("u2*u1 =", u2.dot(u1))

The sqaured size of u2 =  1.0
u2*u1 = -1.741861189847285e-16


In [ ]:
# Find the second nice basis vector:
t3 = r3 - (r3.dot(u1)) * u1 - (r3.dot(u2)) * u2
# Subtract off the nice basis vectors:

# Find the size of t3:
n3 = np.sqrt(t3.dot(t3))

# So u3 = (1/n3) * t3
u3 = (1/n3) * t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [ ]:
print("The sqaured size of u3 = ", u3.dot(u3))
print("u3*u1 =", u3.dot(u1))
print("u3*u2 =", u3.dot(u2))

The sqaured size of u3 =  0.9999999999999998
u3*u1 = -1.0146536357569526e-17
u3*u2 = -6.967444759389139e-16


In [ ]:
# Find the second nice basis vector:
t4 = r4 - (r4.dot(u1)) * u1 - (r4.dot(u2)) * u2 - (r4.dot(u3)) * u3
# Subtract off the nice basis vectors:

# Find the size of t4:
n4 = np.sqrt(t4.dot(t4))

# So u4 = (1/n4) * t4
u4 = (1/n4) * t4
u4

array([-1.23168186e-16, -8.32050294e-01,  1.23168186e-16,  5.54700196e-01])

In [ ]:
print("The sqaured size of u4 = ", u4.dot(u4))
print("u4*u1 =", u4.dot(u1))
print("u4*u2 =", u4.dot(u2))
print("u4*u3 =", u4.dot(u3))

The sqaured size of u4 =  1.0000000000000002
u4*u1 = 4.3370130851795835e-33
u4*u2 = -1.203390859898517e-15
u4*u3 = 8.709305949236507e-17
